import 'package:flutter/widgets.dart';

const gap0 = SizedBox();

const vGap2 = SizedBox(height: 2);
const vGap4 = SizedBox(height: 4);
const vGap8 = SizedBox(height: 8);
const vGap12 = SizedBox(height: 12);
const vGap16 = SizedBox(height: 16);
const vGap20 = SizedBox(height: 20);
const vGap24 = SizedBox(height: 24);
const vGap28 = SizedBox(height: 28);
const vGap32 = SizedBox(height: 32);
const vGap36 = SizedBox(height: 36);
const vGap40 = SizedBox(height: 40);
const vGap44 = SizedBox(height: 44);
const vGap48 = SizedBox(height: 48);
const vGap52 = SizedBox(height: 52);
const vGap56 = SizedBox(height: 56);
const vGap60 = SizedBox(height: 60);
const vGap64 = SizedBox(height: 64);
const vGap68 = SizedBox(height: 68);
const vGap72 = SizedBox(height: 72);
const vGap76 = SizedBox(height: 76);
const vGap80 = SizedBox(height: 80);

const hGap2 = SizedBox(width: 2);
const hGap4 = SizedBox(width: 4);
const hGap8 = SizedBox(width: 8);
const hGap12 = SizedBox(width: 12);
const hGap16 = SizedBox(width: 16);
const hGap20 = SizedBox(width: 20);
const hGap24 = SizedBox(width: 24);
const hGap28 = SizedBox(width: 28);
const hGap32 = SizedBox(width: 32);
const hGap36 = SizedBox(width: 36);
const hGap40 = SizedBox(width: 40);
const hGap44 = SizedBox(width: 44);
const hGap48 = SizedBox(width: 48);
const hGap52 = SizedBox(width: 52);
const hGap56 = SizedBox(width: 56);
const hGap60 = SizedBox(width: 60);
const hGap64 = SizedBox(width: 64);
const hGap68 = SizedBox(width: 68);
const hGap72 = SizedBox(width: 72);
const hGap76 = SizedBox(width: 76);
const hGap80 = SizedBox(width: 80);
